### ISSUE TITLE
Implement Scale Codec Decorator

### ISSUE THREAD

**Issue by Lohann** [rankanizer/polkadart#13]
## Description

- [x] #23 
- [x] #24 
- [x] #25 
- [x] #26

**Comment by gabrielokura** [comment]
## FIrst: Implementation of code generator using annotations 

## Description 
Implementation of scale-codec decorators with dart code generator and annotations. The main concept is about generating classes with the right scale codec methods.

## Acceptance Criteria
- must create a new .g.dart file with the class extension when user writes the decorator above class name.

**Comment by gabrielokura** [comment]
## Second: Addition of substrate primitive types on Polkadart code generator

## Description 
Implementation of scale-codec decorators with dart code generator and annotations. 
In this step we need to add new decorators types that match substrate datatypes and will be used on class encode and decode methods

## Acceptance Criteria
- when user writes the decorator of some type before variable declaration, the package must create a new .g.dart file with that variable parsed

**Comment by gabrielokura** [comment]
## Third: Implementation of class decoding

## Description 
Implementation of the method 'decode' on any class by creating a new dart file and without writing this method on each one 

## Acceptance Criteria
- must create a new .g.dart file with the class extension, including decode function.

**Comment by gabrielokura** [comment]
## Third: Implementation of class encoding

## Description 
Implementation of the method 'encode' on any class by creating a new dart file and without writing this method on each one 

## Acceptance Criteria
- must create a new .g.dart file with the class extension, including encode function.

**Comment by gabrielokura** [comment]
@LuizaJurimetric

**Comment by gabrielokura** [comment]
Will be solved on Milestone 2
