### ISSUE TITLE
100% testing coverage for Scale-Codec

### ISSUE THREAD

**Issue by Lohann** [rankanizer/polkadart#16]
- [x] Test Constants Encode/Decode
- [x] Test Events Encode/Decode
- [x] Test Extrinsic Encode/Decode
- [x] Edge case scenarios where exception must occur.
- [x] Types testing

### Requirements:
- **At least 99% of the code coverage is needed to close this issue.**
- **Well documented code.**

**Comment by justkawal** [comment]
99% Test Coverage achieved.
