### ISSUE TITLE
how to use polkadart to query account balance

### ISSUE THREAD

**Issue by xuanwenchao** [rankanizer/polkadart#309]
how to use polkadart to query account balance
like this in js: api.query.balances.account
thanks for your help.

**Comment by Lohann** [comment]
Hi @xuanwenchao, from which blockchain do you want to query data? Those are the steps:

1 - Create a new project 
```bash
dart create -t console project-name-here
cd project-name-here
```
2 - Add those dependencies to `pubspec.yaml`
```yaml
...
dependencies:
  polkadart: ^0.1.0
  ss58: ^1.1.0

dev_dependencies:
  ...
  polkadart_cli: ^0.1.0

polkadart:
  output_dir: bin/generated
  chains:
    polkadot: wss://rpc.polkadot.io
``` 
Remember to replace `polkadot: wss://rpc.polkadot.io` with the name of the chain and url of the RPC node you want to connect to, you can find a list of RPC nodes here:
[github.com/polkadot-js/apps/blob/master/packages/apps-config/src/endpoints/productionRelayPolkadot.ts](https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/endpoints/productionRelayPolkadot.ts#L714-L743)

3 - Run following command for generate the Dart types from polkadot metadata:
```bash
dart run polkadart_cli:generate -v
```

4 - Replace the contents of `bin/project_name_here.dart` with following sample code:
```dart
import 'package:ss58/ss58.dart' show Address;
import './generated/polkadot/polkadot.dart' show Polkadot;

void main(List<String> arguments) async {
  // Connect to the RPC node
  final Polkadot polkadot = Polkadot.url(Uri.parse('wss://rpc.polkadot.io'));

  // Account from SS58 address
  final account = Address.decode('19t9Q2ay58hMDaeg6eeBhqmHsRnc2jDMV3cYYw9zbc59HLj');

  // Retrieve Account Balance
  final accountInfo = await polkadot.query.system.account(account.pubkey);
  print('Balance: ${accountInfo.data.free}');

  // Retrieve Runtime Version
  final runtimeVersion = await polkadot.rpc.state.getRuntimeVersion();
  print('Runtime Version: ${runtimeVersion.specVersion}');

  // Disconnect
  await polkadot.disconnect();
}
```

5 - For run the code above, just run:
```bash
dart run
```

**Comment by Lohann** [comment]
Same steps can be applied to flutter projects

**Comment by xuanwenchao** [comment]
@Lohann am i using the polkadart_cli to generate it necessary, it is an output error after running dart run polkadart_cli:generate -v

this is my config that uses the local chain.

<img width="533" alt="截屏2023-07-01 19 28 20" src="https://github.com/rankanizer/polkadart/assets/1876277/7a791da3-1f71-48c3-81d1-6a0eb675c28e">

-<130:%>- dart run polkadart_cli:generate -v

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ The Dart tool uses Google Analytics to report feature usage statistics     ║
  ║ and to send basic crash reports. This data is used to help improve the     ║
  ║ Dart platform and tools over time.                                         ║
  ║                                                                            ║
  ║ To disable reporting of analytics, run:                                    ║
  ║                                                                            ║
  ║   dart --disable-analytics                                                 ║
  ║                                                                            ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Could not find a file named "pubspec.yaml" in "/Users/xuanwenchao/.pub-cache/hosted/pub.dartlang.org/args-2.4.1".
#0      new Pubspec.load (package:pub/src/pubspec.dart:306:7)
#1      new Package.load (package:pub/src/package.dart:128:29)
#2      SystemCache.load (package:pub/src/system_cache.dart:105:20)
#3      Entrypoint._createPackageGraph (package:pub/src/entrypoint.dart:121:63)
#4      Entrypoint.packageGraph (package:pub/src/entrypoint.dart:116:54)
#5      getExecutableForCommand (package:pub/src/executable.dart:339:19)
#6      RunCommand.run (package:dartdev/src/commands/run.dart:250:32)
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#8      DartdevRunner.runCommand (package:dartdev/dartdev.dart:231:30)
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
#10     new Future.sync (dart:async/future.dart:302:31)
#11     CommandRunner.run (package:args/command_runner.dart:119:14)
#12     runDartdev (package:dartdev/dartdev.dart:66:29)
#13     main (file:///opt/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

**Comment by xuanwenchao** [comment]
this is my local chain.
<img width="1506" alt="截屏2023-07-01 20 13 43" src="https://github.com/rankanizer/polkadart/assets/1876277/5610def1-a7b6-4276-8b1a-ec715cc65eb0">

**Comment by xuanwenchao** [comment]
I have fixed it, thank you again!
```
polkadart:
  output_dir: lib/generated
  chains:
    polkadot: 'ws://127.0.0.1:9944'
```
