### ISSUE TITLE
How to call custom [pallet::call] in a new pallet directory?

### ISSUE THREAD

**Issue by xuanwenchao** [rankanizer/polkadart#311]
polkadart is a perfect framework for me, I decide to use this framework in our project, but before it I have some question to consult.

I have generated the polkadot with dart run polkadart_cli:generate -v
and the below code looks good
```j
final Polkadot polkadot = Polkadot.url(Uri.parse(network_url));
final account_alice = Address.decode(userList[0]['ss58'].toString());
final accountInfo_alice = await polkadot.query.system.account(account_alice.pubkey);
```

How to call custom [pallet::call] in a new pallet directory? eg. My pallet name is PA the method name of [pallet::call] is PAM in the PA directory.

thanks

**Comment by Lohann** [comment]
After running `polkadart_cli:generate -v` it will automatically generate the pallet methods and objects statically, everytime you update the pallet, you also need to re-run `polkadart_cli:generate -v`.

You can see the available methods at `generated/polkadot/pallets/<name_of_the_pallet_here>.dart`, currently only read-only operations are possible, support for signed extrinsics is work in progress, so if `pallet::call` is an extrinsic is not possible to call it in the current version.

**Comment by xuanwenchao** [comment]
thanks for your reply
